name: "Infra Provisioning"
on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"
  workflow_dispatch:
    inputs:
      terraform-apply:
        description: "Apply Terraform"
        required: false
        default: "false"

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: "terraform-credentials.json"
      TF_VAR_db_user: ${{ secrets.DB_USER }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2

      - name: Create file from secrets
        working-directory: terraform
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | base64 --decode > terraform-credentials.json

      - name: Terraform init
        id: terraform-init
        if: always()
        working-directory: terraform
        run: terraform init

      - name: Terraform validate
        id: terraform-validate
        if: always()
        working-directory: terraform
        run: terraform validate

      - name: Terraform plan
        id: terraform-plan
        working-directory: terraform
        run: terraform plan -var-file=environments/dev.tfvars

      - name: Terraform apply
        id: terraform-apply
        if: github.event.inputs.terraform_apply == 'true'
        working-directory: terraform
        run: terraform apply -auto-approve -var-file=environments/dev.tfvars
